### ISSUE TITLE
Poker_rgb_event

### ISSUE THREAD

**Issue by a1wj1** [Event-AHU/TSCFormer#1]
请问Poker_rgb_event文件夹里面是什么数据？如何生成？感谢回复！

**Comment by wangxiao5791509** [comment]
@a1wj1  如果可以的话，建议开一个 issues 来讨论，别在多个项目上开多个 issues。

**Comment by honoryaoyao** [comment]
RGB和Event两种模态的图像，格式如下
poker
-action_001
--dvSave-xxx
---aps
----00000000.png
----..........
----    .
----    .
----    .
----..........
----00000099.png
---dvs
----00000000.png
----..........
----    .
----    .
----    .
----..........
----00000099.png
