### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by a1wj1** [Event-AHU/TSCFormer#2]
你好，请问mmengine的版本是要多少合适？我用0.7.1报错，0.10.2也报错

File "TSCFormer-main/mmaction2/mmaction/engine/optimizers/tsm_optim_wrapper_constructor.py", line 4, in <module>
    from mmengine.utils.dl_utils.parrots_wrapper import (SyncBatchNorm_, _BatchNorm, _ConvNd, LayerNorm)
ImportError: cannot import name 'LayerNorm' from 'mmengine.utils.dl_utils.parrots_wrapper'

**Comment by honoryaoyao** [comment]
我使用的是mmengine 0.9.0 ，你需要在mmengine.utils.dl_utils.parrots_wrapper的_get_norm()中添加一个LayerNorm
